// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/google/wire"
	"github.com/kodaikumatani/grpc-authentication-go/internal"
	"github.com/kodaikumatani/grpc-authentication-go/internal/app"
	"github.com/kodaikumatani/grpc-authentication-go/internal/app/greeter"
	"github.com/kodaikumatani/grpc-authentication-go/internal/authn"
	"github.com/kodaikumatani/grpc-authentication-go/internal/authn/firebase"
)

// Injectors from wire.go:

func initializeServices(ctx context.Context) (*services, error) {
	greeterServer := greeter.NewHandler()
	registrar := app.NewRegistrar(greeterServer)
	verifier, err := firebase.NewVerifier(ctx)
	if err != nil {
		return nil, err
	}
	mainServices := &services{
		Registrar: registrar,
		Verifier:  verifier,
	}
	return mainServices, nil
}

// wire.go:

type services struct {
	*app.Registrar
	Verifier authn.Verifier
}

var set = wire.NewSet(internal.Set, wire.Struct(new(services), "*"))
